services:
  ms-franchise-neg:
    build: .
    container_name: ms-franchise-neg
    ports:
      - "8001:8001"
    environment:
      - DB_CONNECTION_STRING=${MONGO_URL}
    networks:
      - spring_network
volumes:
  mongodb_data:
    name: mongo_nequi_data
networks:
  spring_network:
    driver: bridge