server:
  port: 8001

spring:
  webflux:
    base-path: /api/v1
  application:
    name: ms-franchise-neg
  data:
    mongodb:
      uri: ${DB_CONNECTION_STRING}

#Project info
app:
  version: @project.version@
  name: @project.name@