apiVersion: v1
kind: Service
metadata:
  name: ms-franchise-service
spec:
  selector:
    app: ms-franchise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer
